name: "build and test"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-and-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v4"
      - name: "install nix"
        uses: "cachix/install-nix-action@v31"
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: "cache nix store"
        uses: "nix-community/cache-nix-action@v7"
        with:
          primary-key: "nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}"
          restore-prefixes-first-match: "nix-${{ runner.os }}-"
          gc-max-store-size-linux: 1G
      - name: "cache opam switch"
        uses: "actions/cache@v3"
        with:
          path: _opam
          key: "oxqr-${{ runner.os }}-${{ hashFiles('*.opam') }}"
          restore-keys: |
            oxqr-${{ runner.os }}-
      - name: "build"
        run: nix develop --command dune build
      - name: "test"
        run: nix develop --command dune runtest
